### ISSUE TITLE
Can I mock a method?

### ISSUE THREAD

**Issue by myst729** [Mercateo/import-inject-loader#3]
Case 1, say, my code is like this:

```js
// ./actions/user
import user from '../apis/user'
export const getUser = () => {
  return user.getUserFromService()
}
```
So my test case is like:

```js
// ./tests/user
import {
  getUser,
  ilOverwriteGetUserFromService,
  ilResetAll
} from 'import-inject-loader?user.getUserFromService!../actions/user';
```

Which does not work because `user.getUserFromService` is not a variable name.

Case 2, I may want to export an object:

```js
// ./actions/user
import user from '../apis/user'
export const userActions = {
  getUser = () => {
    return user.getUserFromService()
  },
  getUserDetail = () => {
    return user.getUserDetailFromService()
  }
}
```
So I guess I should do it this way:

```js
// ./tests/user
import {
  userActions,
  ilOverwriteGetUserFromService,
  ilResetAll
} from 'import-inject-loader?user.getUserFromService!../actions/user';

...
userActions.getUser()
...
```
Is this on the plan?

**Comment by myst729** [comment]
Currently I'm using **inject-loader** to test my vuex actions. https://vuex.vuejs.org/en/testing.html#testing-actions

It works but looks like a bit boring.

**Comment by floric** [comment]
I'm currently not sure. I didn't touch this code since creation. I'll have a look when I have time.

**Comment by donaldpipowitch** [comment]
> Is this on the plan?

We haven't needed it yet. When we need to mock `user.getUserFromService` we'd currently just mock `user`. Maybe we'd accept a PR, if the change is not too complicated?
